# Generated by Django 3.2.9 on 2021-11-09 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cutcut', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='author',
        ),
        migrations.AddField(
            model_name='url',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
